### ISSUE TITLE
Error 500 createtemplates.ps1

### ISSUE THREAD

**Issue by ben71fl** [xrsxj/HuduSync#1]
When connecting it looks like it goes through but i get back error 500 on powershell. 

Here is the log on the hudu

| D, [2020-05-18T20:47:23.849210 #58] DEBUG -- : [33c68427-cea3-414a-9aa7-49e1a021303a]   ApiKey Load (0.3ms)  SELECT "api_keys".* FROM "api_keys" WHERE "api_keys"."token" = $1 LIMIT $2  [["token", "keywashere"], ["LIMIT", 1]]
app_1          | D, [2020-05-18T20:47:23.850162 #58] DEBUG -- : [33c68427-cea3-414a-9aa7-49e1a021303a]   Account Load (0.2ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
app_1          | I, [2020-05-18T20:47:23.851557 #58]  INFO -- : [33c68427-cea3-414a-9aa7-49e1a021303a] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.5ms | Allocations: 1066)
app_1          | D, [2020-05-18T20:47:23.851659 #58] DEBUG -- : [33c68427-cea3-414a-9aa7-49e1a021303a] Invalid parameter 'include_passwords' value "False": Must be one of: <code>true</code>, <code>false</code>. excluded from capture: DSN not set

If i try to just run the import I get an SSL/TLS mismatch - this could be because of Cloudflare in front but I tried taking it off too and didnt help.

**Comment by xrsxj** [comment]
Just pushed a commit to fix that, looks like it expects true and false to be boolean instead of strings.

**Comment by xrsxj** [comment]
Hmmm the ssl/tls mismatch are you giving it the IP address or the domain name?

**Comment by ben71fl** [comment]
Im giving it the domain name. I thought maybe it was cloudflare so I took it off but didn’t seem to change it. I was going to try using the ignore self signed certificate script but its definitely a valid SSL

**Comment by xrsxj** [comment]
Which version of powershell are you running the script from?  I'm having trouble recreating the SSL/TLS error.

**Comment by ben71fl** [comment]
I think I got past that now and the import works but the template creator still has the same errors. I am going to try to create all the fields manually because the import function definitely ‘worked’ it just couldn’t match the companies.

**Comment by xrsxj** [comment]
Gotcha, yeah the template creator was never tested really since i didn't want to blow up my whole setup to verify it.
